### ISSUE TITLE
Malformed helptoc.xml causing issues when running setup script in MATLAB

### ISSUE THREAD

**Issue by dkunderuMW** [CPFL/Autoware_Toolbox#1]
Running the setup script for the Autoware Toolbox submission on MATLAB File exchange gives  the following error:
```
Error using builddocsearchdb (line 38)
Could not write search database.

Error in autoware_toolbox_setup (line 92)
builddocsearchdb(path_doc_folder);
```

The issue is being caused due to a malformed `helptoc.xml` file. 

Please consider replacing the file with teh XML file in 
[helptoc.zip](https://github.com/CPFL/Autoware_Toolbox/files/3173644/helptoc.zip)

**Comment by nxt-norick** [comment]
Thanks for your report.
I'm going to fix it.
